program OposConfig;

uses
  Forms,
  SysUtils,
  gnugettext,
  Oposhi in '..\Opos\Oposhi.pas',
  OposUtils in '..\Opos\OposUtils.pas',
  Opos in '..\Opos\Opos.pas',
  OposEvents in '..\Opos\OposEvents.pas',
  OPOSException in '..\Opos\OposException.pas',
  OposFptr in '..\Opos\OposFptr.pas',
  OposFptrhi in '..\Opos\OposFptrhi.pas',
  OposFptrUtils in '..\Opos\OposFptrUtils.pas',
  OposDevice in '..\Opos\OposDevice.pas',
  fmuMain in 'Fmu\fmuMain.pas' {fmMain},
  fmuDevice in 'Fmu\fmuDevice.pas' {fmDevice},
  fmuPages in 'Fmu\fmuPages.pas' {fmPages},
  untUtil in 'Units\untUtil.pas',
  DriverError in '..\Shared\DriverError.pas',
  VersionInfo in '..\Shared\VersionInfo.pas',
  DebugUtils in '..\Shared\DebugUtils.pas',
  OposDaisyLib_TLB in '..\OposDaisy\OposDaisyLib_TLB.pas',
  OposFiscalPrinter_1_12_Lib_TLB in '..\Opos\OposFiscalPrinter_1_12_Lib_TLB.pas',
  BaseForm in '..\Shared\BaseForm.pas',
  untPages in 'Units\untPages.pas',
  FptrTypes in 'Units\FptrTypes.pas',
  FileUtils in '..\Shared\FileUtils.pas',
  LogFile in '..\Shared\LogFile.pas',
  FiscalPrinterDevice in 'Units\FiscalPrinterDevice.pas',
  WException in '..\Shared\WException.pas',
  fmuFptrLog in 'Fmu\fmuFptrLog.pas' {fmFptrLog},
  PrinterParameters in '..\Shared\PrinterParameters.pas',
  DriverContext in '..\Shared\DriverContext.pas',
  fmuPrinter in 'Fmu\fmuPrinter.pas' {fmPrinter},
  PrinterParametersX in '..\Shared\PrinterParametersX.pas',
  PrinterParametersIni in '..\Shared\PrinterParametersIni.pas',
  TntIniFiles in '..\Shared\TntIniFiles.pas',
  SmIniFile in '..\Shared\SmIniFile.pas',
  StringUtils in '..\Shared\StringUtils.pas',
  JsonUtils in '..\Shared\JsonUtils.pas',
  OposPOSPrinter_CCO_TLB in '..\Opos\OposPOSPrinter_CCO_TLB.pas',
  OposPtr in '..\Opos\OposPtr.pas',
  OposPtrUtils in '..\Opos\OposPtrUtils.pas',
  OposPtrhi in '..\Opos\OposPtrhi.pas',
  OposEventsRCS in '..\Opos\OposEventsRCS.pas',
  OposSemaphore in '..\Opos\OposSemaphore.pas',
  PrinterParametersReg in '..\Shared\PrinterParametersReg.pas',
  VatRate in '..\Shared\VatRate.pas',
  uLkJSON in '..\Shared\uLkJSON.pas',
  SerialPorts in '..\Shared\SerialPorts.pas',
  SerialPort in '..\Shared\SerialPort.pas',
  PrinterPort in '..\Shared\PrinterPort.pas',
  DeviceNotification in '..\Shared\DeviceNotification.pas',
  PortUtil in '..\Shared\PortUtil.pas',
  TextReport in '..\Shared\TextReport.pas',
  OposServiceDevice19 in '..\Opos\OposServiceDevice19.pas',
  NotifyThread in '..\Shared\NotifyThread.pas',
  ByteUtils in '..\Shared\ByteUtils.pas',
  Semaphore in '..\Opos\Semaphore.pas',
  DaisyFiscalPrinter in '..\OposDaisy\units\DaisyFiscalPrinter.pas',
  FiscalPrinterState in '..\OposDaisy\units\FiscalPrinterState.pas',
  CustomReceipt in '..\OposDaisy\units\CustomReceipt.pas',
  ServiceVersion in '..\Shared\ServiceVersion.pas',
  DeviceService in '..\Shared\DeviceService.pas',
  CashReceipt in '..\OposDaisy\units\CashReceipt.pas',
  SalesReceipt in '..\OposDaisy\units\SalesReceipt.pas',
  ReceiptItem in '..\OposDaisy\units\ReceiptItem.pas',
  MathUtils in '..\OposDaisy\units\MathUtils.pas',
  uZintBarcode in '..\Shared\uZintBarcode.pas',
  uZintInterface in '..\Shared\uZintInterface.pas',
  SocketPort in '..\Shared\SocketPort.pas',
  MockPrinterPort in '..\Shared\MockPrinterPort.pas',
  RawPrinterPort in '..\Shared\RawPrinterPort.pas',
  Translation in '..\Shared\Translation.pas',
  DirectIOAPI in '..\OposDaisy\units\DirectIOAPI.pas',
  xmlParser in '..\Shared\XMLParser.pas',
  PrinterTypes in '..\Shared\PrinterTypes.pas',
  BarcodeUtils in '..\Shared\BarcodeUtils.pas',
  DaisyPrinter in '..\OposDaisy\units\DaisyPrinter.pas',
  StrUtil in '..\Shared\StrUtil.pas',
  VariantUtils in '..\Shared\VariantUtils.pas',
  FiscalReceipt in '..\OposDaisy\units\FiscalReceipt.pas',
  fmuLogo in '..\OposDaisy\Fmu\fmuLogo.pas' {fmLogo},
  fmuFptrConnection in 'Fmu\fmuFptrConnection.pas' {fmFptrConnection};

{$R *.RES}
{$R WindowsXP.RES}

begin
  Application.Initialize;
  Application.CreateForm(TfmMain, fmMain);
  Application.CreateForm(TfmFptrConnection, fmFptrConnection);
  Application.Run;
end.



