program OposConfig;

uses
  Forms,
  SysUtils,
  gnugettext,
  Oposhi in '..\Opos\Oposhi.pas',
  OposUtils in '..\Opos\OposUtils.pas',
  Opos in '..\Opos\Opos.pas',
  OposEvents in '..\Opos\OposEvents.pas',
  OPOSException in '..\Opos\OposException.pas',
  OposFptr in '..\Opos\OposFptr.pas',
  OposFptrhi in '..\Opos\OposFptrhi.pas',
  OposFptrUtils in '..\Opos\OposFptrUtils.pas',
  OposDevice in '..\Opos\OposDevice.pas',
  fmuMain in 'Fmu\fmuMain.pas' {fmMain},
  fmuDevice in 'Fmu\fmuDevice.pas' {fmDevice},
  fmuPages in 'Fmu\fmuPages.pas' {fmPages},
  untUtil in 'Units\untUtil.pas',
  DriverError in '..\Shared\DriverError.pas',
  VersionInfo in '..\Shared\VersionInfo.pas',
  DebugUtils in '..\Shared\DebugUtils.pas',
  OposDatecsLib_TLB in '..\OposDatecs\OposDatecsLib_TLB.pas',
  OposFiscalPrinter_1_12_Lib_TLB in '..\Opos\OposFiscalPrinter_1_12_Lib_TLB.pas',
  BaseForm in '..\Shared\BaseForm.pas',
  untPages in 'Units\untPages.pas',
  FptrTypes in 'Units\FptrTypes.pas',
  FileUtils in '..\Shared\FileUtils.pas',
  LogFile in '..\Shared\LogFile.pas',
  FiscalPrinterDevice in 'Units\FiscalPrinterDevice.pas',
  WException in '..\Shared\WException.pas',
  fmuFptrLog in 'Fmu\fmuFptrLog.pas' {fmFptrLog},
  PrinterParameters in '..\Shared\PrinterParameters.pas',
  DriverContext in '..\Shared\DriverContext.pas',
  fmuPrinter in 'Fmu\fmuPrinter.pas' {fmPrinter},
  PrinterParametersX in '..\Shared\PrinterParametersX.pas',
  PrinterParametersIni in '..\Shared\PrinterParametersIni.pas',
  TntIniFiles in '..\Shared\TntIniFiles.pas',
  SmIniFile in '..\Shared\SmIniFile.pas',
  StringUtils in '..\Shared\StringUtils.pas',
  RegExpr in '..\Shared\RegExpr.pas',
  fmuFptrReceipt in 'Fmu\fmuFptrReceipt.pas' {fmFptrReceipt},
  fmuFptrTrailer in 'Fmu\fmuFptrTrailer.pas' {fmFptrTrailer},
  JsonUtils in '..\Shared\JsonUtils.pas',
  fmuFptrConnection in 'Fmu\fmuFptrConnection.pas' {fmFptrConnection},
  OposPOSPrinter_CCO_TLB in '..\Opos\OposPOSPrinter_CCO_TLB.pas',
  OposPtr in '..\Opos\OposPtr.pas',
  OposPtrUtils in '..\Opos\OposPtrUtils.pas',
  OposPtrhi in '..\Opos\OposPtrhi.pas',
  OposEventsRCS in '..\Opos\OposEventsRCS.pas',
  OposSemaphore in '..\Opos\OposSemaphore.pas',
  PrinterParametersReg in '..\Shared\PrinterParametersReg.pas',
  fmuFptrMiscParams in 'Fmu\fmuFptrMiscParams.pas' {fmFptrMiscParams},
  fmuFptrVatRate in 'Fmu\fmuFptrVatRate.pas' {fmFptrVatRate},
  VatRate in '..\Shared\VatRate.pas',
  uLkJSON in '..\Shared\uLkJSON.pas',
  fmuFptrPayType in 'Fmu\fmuFptrPayType.pas' {fmFptrPayType},
  SerialPorts in '..\Shared\SerialPorts.pas',
  SerialPort in '..\Shared\SerialPort.pas',
  PrinterPort in '..\Shared\PrinterPort.pas',
  DeviceNotification in '..\Shared\DeviceNotification.pas',
  PortUtil in '..\Shared\PortUtil.pas',
  TextReport in '..\Shared\TextReport.pas',
  OposServiceDevice19 in '..\Opos\OposServiceDevice19.pas',
  NotifyThread in '..\Shared\NotifyThread.pas',
  ByteUtils in '..\Shared\ByteUtils.pas',
  Semaphore in '..\Opos\Semaphore.pas',
  DatecsFiscalPrinter in '..\OposDatecs\units\DatecsFiscalPrinter.pas',
  FiscalPrinterState in '..\OposDatecs\units\FiscalPrinterState.pas',
  CustomReceipt in '..\OposDatecs\units\CustomReceipt.pas',
  NonfiscalDoc in '..\OposDatecs\units\NonfiscalDoc.pas',
  ServiceVersion in '..\Shared\ServiceVersion.pas',
  DeviceService in '..\Shared\DeviceService.pas',
  CashInReceipt in '..\OposDatecs\units\CashInReceipt.pas',
  CashOutReceipt in '..\OposDatecs\units\CashOutReceipt.pas',
  SalesReceipt in '..\OposDatecs\units\SalesReceipt.pas',
  ReceiptItem in '..\OposDatecs\units\ReceiptItem.pas',
  MathUtils in '..\OposDatecs\units\MathUtils.pas',
  TextDocument in '..\OposDatecs\units\TextDocument.pas',
  uZintBarcode in '..\Shared\uZintBarcode.pas',
  uZintInterface in '..\Shared\uZintInterface.pas',
  SocketPort in '..\Shared\SocketPort.pas',
  ReceiptTemplate in '..\Shared\ReceiptTemplate.pas',
  MockPrinterPort in '..\Shared\MockPrinterPort.pas',
  RawPrinterPort in '..\Shared\RawPrinterPort.pas',
  Translation in '..\Shared\Translation.pas',
  fmuFptrHeader in 'Fmu\fmuFptrHeader.pas' {fmFptrHeader},
  DirectIOAPI in '..\OposDatecs\units\DirectIOAPI.pas',
  xmlParser in '..\Shared\XMLParser.pas',
  PrinterTypes in '..\Shared\PrinterTypes.pas',
  BarcodeUtils in '..\Shared\BarcodeUtils.pas',
  DatecsPrinter in '..\OposDatecs\units\DatecsPrinter.pas',
  ExellioFrame in '..\OposDatecs\units\ExellioFrame.pas',
  DatecsTypes in '..\OposDatecs\units\DatecsTypes.pas',
  SerialPort2 in '..\Shared\SerialPort2.pas',
  LogFile2 in '..\Shared\LogFile2.pas',
  StrUtil in '..\Shared\StrUtil.pas',
  DriverError2 in '..\OposDatecs\units\DriverError2.pas',
  VariantUtils in '..\Shared\VariantUtils.pas';

{$R *.RES}
{$R WindowsXP.RES}

begin
  Application.Initialize;
  Application.CreateForm(TfmMain, fmMain);
  Application.Run;
end.



