program AcceptanceTest;

uses
  SysUtils,
  TestFramework,
  GUITestRunner,
  LogFile in '..\..\src\Shared\LogFile.pas',
  Opos in '..\..\src\Opos\Opos.pas',
  OposUtils in '..\..\src\Opos\OposUtils.pas',
  Oposhi in '..\..\src\Opos\Oposhi.pas',
  OposStat in '..\..\src\Opos\OposStat.pas',
  OposSemaphore in '..\..\src\Opos\OposSemaphore.pas',
  WException in '..\..\src\Shared\WException.pas',
  duDPPrintTest in 'units\duDPPrintTest.pas',
  OPOSException in '..\..\src\Opos\OposException.pas',
  OposServiceDevice19 in '..\..\src\Opos\OposServiceDevice19.pas',
  OposFptr in '..\..\src\Opos\OposFptr.pas',
  OposEvents in '..\..\src\Opos\OposEvents.pas',
  OposFptrUtils in '..\..\src\Opos\OposFptrUtils.pas',
  OposFptrhi in '..\..\src\Opos\OposFptrhi.pas',
  NotifyThread in '..\..\src\Shared\NotifyThread.pas',
  StringUtils in '..\..\src\Shared\StringUtils.pas',
  FileUtils in '..\..\src\Shared\FileUtils.pas',
  PrinterPort in '..\..\src\Shared\PrinterPort.pas',
  ByteUtils in '..\..\src\Shared\ByteUtils.pas',
  SerialPort in '..\..\src\Shared\SerialPort.pas',
  DeviceNotification in '..\..\src\Shared\DeviceNotification.pas',
  PortUtil in '..\..\src\Shared\PortUtil.pas',
  TextReport in '..\..\src\Shared\TextReport.pas',
  SocketPort in '..\..\src\Shared\SocketPort.pas',
  DriverError in '..\..\src\Shared\DriverError.pas',
  DebugUtils in '..\..\src\Shared\DebugUtils.pas',
  DaisyPrinter in '..\..\src\OposDaisy\units\DaisyPrinter.pas',
  duDaisyFiscalPrinter in 'units\duDaisyFiscalPrinter.pas',
  OPOSDaisyLib_TLB in '..\..\src\OposDaisy\OPOSDaisyLib_TLB.pas',
  DaisyFiscalPrinter in '..\..\src\OposDaisy\units\DaisyFiscalPrinter.pas',
  VersionInfo in '..\..\src\Shared\VersionInfo.pas',
  FiscalPrinterState in '..\..\src\OposDaisy\units\FiscalPrinterState.pas',
  ServiceVersion in '..\..\src\Shared\ServiceVersion.pas',
  DeviceService in '..\..\src\Shared\DeviceService.pas',
  SerialPorts in '..\..\src\Shared\SerialPorts.pas',
  ReceiptItem in '..\..\src\OposDaisy\units\ReceiptItem.pas',
  MathUtils in '..\..\src\OposDaisy\units\MathUtils.pas',
  PrinterTypes in '..\..\src\Shared\PrinterTypes.pas',
  xmlParser in '..\..\src\Shared\XMLParser.pas',
  TntIniFiles in '..\..\src\Shared\TntIniFiles.pas',
  SmIniFile in '..\..\src\Shared\SmIniFile.pas',
  DirectIOAPI in '..\..\src\OposDaisy\units\DirectIOAPI.pas',
  CashReceipt in '..\..\src\OposDaisy\units\CashReceipt.pas',
  FiscalReceipt in '..\..\src\OposDaisy\units\FiscalReceipt.pas',
  SalesReceipt in '..\..\src\OposDaisy\units\SalesReceipt.pas',
  OposEventsRCS in '..\..\src\Opos\OposEventsRCS.pas',
  oleFiscalPrinter in '..\..\src\OposDaisy\units\oleFiscalPrinter.pas',
  duDPDataTest in 'units\duDPDataTest.pas',
  fmuLogo in '..\..\src\OposDaisy\Fmu\fmuLogo.pas' {fmLogo},
  BaseForm in '..\..\src\Shared\BaseForm.pas',
  PrinterParameters in '..\..\src\OposDaisy\units\PrinterParameters.pas',
  PrinterParametersX in '..\..\src\OposDaisy\units\PrinterParametersX.pas',
  PrinterParametersReg in '..\..\src\OposDaisy\units\PrinterParametersReg.pas';

{$R *.RES}
{$R ..\..\src\OposDaisy\OposDaisy.tlb}

begin
  TGUITestRunner.RunTest(RegisteredTests);
end.
