library OposDatecs;

uses
  Opos in '..\Opos\Opos.pas',
  Oposhi in '..\Opos\Oposhi.pas',
  OposFptr in '..\Opos\OposFptr.pas',
  OposUtils in '..\Opos\OposUtils.pas',
  OposFptrhi in '..\Opos\OposFptrhi.pas',
  OposException in '..\Opos\OposException.pas',
  WException in '..\Shared\WException.pas',
  oleFiscalPrinter in 'Units\oleFiscalPrinter.pas',
  LogFile in '..\Shared\LogFile.pas',
  OposFptrUtils in '..\Opos\OposFptrUtils.pas',
  DatecsFiscalPrinter in 'units\DatecsFiscalPrinter.pas',
  OposDatecsLib_TLB in 'OposDatecsLib_TLB.pas',
  OposServiceDevice19 in '..\Opos\OposServiceDevice19.pas',
  OposEvents in '..\Opos\OposEvents.pas',
  OposSemaphore in '..\Opos\OposSemaphore.pas',
  NotifyThread in '..\Shared\NotifyThread.pas',
  VersionInfo in '..\Shared\VersionInfo.pas',
  OposEventsRCS in '..\Opos\OposEventsRCS.pas',
  DebugUtils in '..\Shared\DebugUtils.pas',
  DriverError in '..\Shared\DriverError.pas',
  JsonUtils in '..\Shared\JsonUtils.pas',
  FiscalPrinterState in 'units\FiscalPrinterState.pas',
  CustomReceipt in 'units\CustomReceipt.pas',
  TextItem in 'units\TextItem.pas',
  MathUtils in 'units\MathUtils.pas',
  NonfiscalDoc in 'units\NonfiscalDoc.pas',
  ServiceVersion in '..\Shared\ServiceVersion.pas',
  DeviceService in '..\Shared\DeviceService.pas',
  CashOutReceipt in 'units\CashOutReceipt.pas',
  CashInReceipt in 'units\CashInReceipt.pas',
  PrinterParameters in '..\Shared\PrinterParameters.pas',
  FileUtils in '..\Shared\FileUtils.pas',
  PrinterParametersX in '..\Shared\PrinterParametersX.pas',
  PrinterParametersIni in '..\Shared\PrinterParametersIni.pas',
  TntIniFiles in '..\Shared\TntIniFiles.pas',
  SmIniFile in '..\Shared\SmIniFile.pas',
  StringUtils in '..\Shared\StringUtils.pas',
  RegExpr in '..\Shared\RegExpr.pas',
  SalesReceipt in 'units\SalesReceipt.pas',
  ReceiptItem in 'units\ReceiptItem.pas',
  TextDocument in 'units\TextDocument.pas',
  PrinterParametersReg in '..\Shared\PrinterParametersReg.pas',
  ComServ in '..\Common\ComServ.pas',
  uLkJSON in '..\Shared\uLkJSON.pas',
  VatRate in '..\Shared\VatRate.pas',
  OposFiscalPrinter_CCO_TLB in '..\Opos\OposFiscalPrinter_CCO_TLB.pas',
  uZintBarcode in '..\Shared\uZintBarcode.pas',
  uZintInterface in '..\Shared\uZintInterface.pas',
  OposDevice in '..\Opos\OposDevice.pas',
  ByteUtils in '..\Shared\ByteUtils.pas',
  PrinterPort in '..\Shared\PrinterPort.pas',
  SerialPort in '..\Shared\SerialPort.pas',
  DeviceNotification in '..\Shared\DeviceNotification.pas',
  PortUtil in '..\Shared\PortUtil.pas',
  TextReport in '..\Shared\TextReport.pas',
  SocketPort in '..\Shared\SocketPort.pas',
  SerialPorts in '..\Shared\SerialPorts.pas',
  ReceiptTemplate in '..\Shared\ReceiptTemplate.pas',
  MockPrinterPort in '..\Shared\MockPrinterPort.pas',
  RawPrinterPort in '..\Shared\RawPrinterPort.pas',
  Translation in '..\Shared\Translation.pas',
  DirectIOAPI in 'units\DirectIOAPI.pas',
  xmlParser in '..\Shared\XMLParser.pas',
  PrinterTypes in '..\Shared\PrinterTypes.pas',
  BarcodeUtils in '..\Shared\BarcodeUtils.pas',
  DatecsPrinter in 'units\DatecsPrinter.pas',
  DatecsTypes in 'units\DatecsTypes.pas',
  StrUtil in '..\Shared\StrUtil.pas',
  VariantUtils in '..\Shared\VariantUtils.pas',
  SerialPort2 in '..\Shared\SerialPort2.pas',
  LogFile2 in '..\Shared\LogFile2.pas',
  DriverError2 in 'units\DriverError2.pas',
  DatecsPrinter2 in 'units\DatecsPrinter2.pas';

exports
  DllGetClassObject,
  DllCanUnloadNow,
  DllRegisterServer,
  DllUnregisterServer;

{$R *.TLB}

{$R *.RES}

begin
end.
